apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: postgres:5432
    database: trading
    user: trading
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
